In [2]:
from google.colab import files

uploaded = files.upload()

Saving StudentsPerformance.csv to StudentsPerformance.csv

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("/content/StudentsPerformance.csv")

In [5]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [7]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [8]:
cat_cols = ['gender', 'race/ethnicity', 'parental level of education',
            'lunch', 'test preparation course']

In [9]:
for col in cat_cols:
    df[col] = df[col].str.strip()

In [10]:
for col in cat_cols:
    print(col, df[col].unique())

gender ['female' 'male']
race/ethnicity ['group B' 'group C' 'group A' 'group D' 'group E']
parental level of education ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
lunch ['standard' 'free/reduced']
test preparation course ['none' 'completed']

In [11]:
subjects = ['math score', 'reading score', 'writing score']

print(df[subjects].describe())

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [12]:
for col in subjects:
    print("\n", col)
    print("Mean:", df[col].mean())
    print("Median:", df[col].median())
    print("Standard Deviation:", df[col].std())
    print("Q1:", df[col].quantile(0.25))
    print("Q3:", df[col].quantile(0.75))

 math score
Mean: 66.089
Median: 66.0
Standard Deviation: 15.163080096009468
Q1: 57.0
Q3: 77.0

 reading score
Mean: 69.169
Median: 70.0
Standard Deviation: 14.60019193725222
Q1: 59.0
Q3: 79.0

 writing score
Mean: 68.054
Median: 69.0
Standard Deviation: 15.195657010869642
Q1: 57.75
Q3: 79.0

In [13]:
df['Total Marks'] = (
    df['math score'] +
    df['reading score'] +
    df['writing score']
)

df['Percentage'] = (df['Total Marks'] / 300) * 100

print(df[['Total Marks', 'Percentage']].head())

   Total Marks  Percentage
0          218   72.666667
1          247   82.333333
2          278   92.666667
3          148   49.333333
4          229   76.333333

In [14]:
for col in subjects:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print("\nOutliers in", col)
    print(outliers[[col]])

Outliers in math score
     math score
17           18
59            0
145          22
338          24
466          26
787          19
842          23
980           8

Outliers in reading score
     reading score
59              17
76              26
211             28
327             23
596             24
980             24

Outliers in writing score
     writing score
59              10
76              22
327             19
596             15
980             23